// This code is called from with HTML. //
// It the creates some HTML H1, H2 and P tags to display on the web page 


// First, lets add some style to our headings
	window.document.write("<style>") 
	window.document.write("h1 {color:blue;} ");
	window.document.write("h2 {color:lightblue;}" );
	window.document.write("</style>");

// now, lets write the HTML code to dispaly something on the web page
window.document.write("<h1>Hello from the outside</h1>");
window.document.write("<h2>This heading is generated by external JavaScript</h2>");

window.document.write("<p>This paragraph also generated by JavaScript code.</p>");

window.document.write("<p>This page's title is :<strong>" + document.title + "<strong></p>");
window.document.write("<p>The HTML page was last modified:<strong> " + document.lastModified +"</strong></p>");

